name: Flutter Basic Check

on:
  push:
    branches:
      - master
      - main
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches: [ "master", "main" ]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed lib test

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run Flutter test
        run: flutter test --dart-define=API_BASE_URL=https://api-j6d6.onrender.com

      - name: Build debug APK
        run: flutter build apk --debug --dart-define=API_BASE_URL=https://api-j6d6.onrender.com
